In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataSet = pd.read_csv("./Datas/8.Data_All_regression.csv")
x = dataSet.iloc[:, :-1].values
y = dataSet.iloc[:, -1:].values

In [13]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression
Lin_regressor =  LinearRegression()
Lin_regressor.fit(x_train, y_train)

LinearRegression()

In [32]:
y_pred = Lin_regressor.predict(x_test)

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9325315554761303

In [40]:
from sklearn.tree import DecisionTreeRegressor
d_regressor = DecisionTreeRegressor(random_state=0)
d_regressor.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [45]:
y_pred_1 = d_regressor.predict(x_test)

In [47]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_1)

0.922905874177941

In [60]:
from sklearn.ensemble import RandomForestRegressor
r_regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
r_regressor.fit(x_train, y_train)

C:\Users\acer\AppData\Local\Temp\ipykernel_5456\868982534.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train, y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

In [69]:
y_pred_2 = r_regressor.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_2)

0.9572232032550486

In [72]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(x_train)
pol_regressor = LinearRegression()
pol_regressor.fit(x_poly, y_train)

LinearRegression()

In [75]:
x_poly_test = poly_reg.fit_transform(x_test)
y_pred_3 = pol_regressor.predict(x_poly_test)

In [76]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_3)

0.9458192605305928